image: docker:stable

stages:
  - info
  - build
  - release
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  BUILD_IMAGE: ${CI_REGISTRY_IMAGE}/build:$CI_COMMIT_SHA   
  
  BUILD_CONFIG_DEV: ""
  BUILD_CONFIG_STAGE: stage
  BUILD_CONFIG_PROD: production

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/
    - dist/

# INFO ===============================
info:
  stage: info
  image: ubuntu:18.04
  tags:
    - linux
  script:
    - echo Reference name=$CI_BUILD_REF_NAME
    - echo Release image=$RELEASE_IMAGE
    - echo Tag=$CI_COMMIT_TAG
  only:
    - debug

# BUILD ===============================
.build_script: &build_script
    stage: build
    image: docker:stable
    tags: 
      - docker
    script: 
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
      - docker build -t $BUILD_IMAGE --build-arg BUILDCONF=$BUILD_CONFIG --build-arg APPVERSION=$BUILD_VERSION .
      - docker push $BUILD_IMAGE

build:branch:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_DEV
    BUILD_VERSION: $CI_COMMIT_SHA
  only:
    - /^(feature|hotfix|release)\/.+$/

build:stage:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_STAGE
    BUILD_VERSION: Staging:$CI_COMMIT_SHORT_SHA
  only:
    - stage

build:master:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_PROD
    BUILD_VERSION: Master:$CI_COMMIT_SHORT_SHA
  only:
    - master

build:production:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_PROD
    BUILD_VERSION: CI_COMMIT_TAG
  only:
    - /^([0-9]+\.){2}([0-9]+)+(\.[0-9]+)?$/
  except:
    - branches


# RELEASE ==============================
.release_script: &release_script
  stage: deploy
  image: docker:stable
  tags: 
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $BUILD_IMAGE    
    - docker login  -u $AZURE_APP_ID -p $AZURE_APP_SECRET $AZURE_ACR_SERVER   
    - docker tag $BUILD_IMAGE $DEPLOY_IMAGE
    - docker push $DEPLOY_IMAGE

release:stage:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:stage
  only:
    - stage

release:master:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:master
  only:
    - master    

release:production:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:$CI_COMMIT_TAG
  only:
    - /^([0-9]+\.){2}([0-9]+)+(\.[0-9]+)?$/
  except:
    - branches

release:latest:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:latest
  only:
    - /^([0-9]+\.){2}([0-9]+)+(\.[0-9]+)?$/
  except:
    - branches


