image: docker:stable

stages:
  - info
  - build
  - release
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  BUILD_IMAGE: ${CI_REGISTRY_IMAGE}/build:$CI_COMMIT_SHA   
  
  BUILD_CONFIG_DEV: ""
  BUILD_CONFIG_STAGE: stage
  BUILD_CONFIG_PROD: production

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/
    - dist/

# INFO ===============================
info:
  stage: info
  image: ubuntu:18.04
  tags:
    - linux
  script:
    - echo Reference name=$CI_BUILD_REF_NAME
    - echo Release image=$RELEASE_IMAGE
    - echo Tag=$CI_COMMIT_TAG
  only:
    - debug

# BUILD ===============================
.build_script: &build_script
    stage: build
    image: docker:stable
    tags: 
      - docker
    script: 
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
      - docker build -t $BUILD_IMAGE --build-arg BUILDCONF=$BUILD_CONFIG --build-arg APPVERSION=$BUILD_VERSION .
      - docker push $BUILD_IMAGE

build:branch:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_DEV
    BUILD_VERSION: $CI_COMMIT_SHA
  only:
    - /^(feature|hotfix|release)\/.+$/

build:stage:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_STAGE
    BUILD_VERSION: Staging:$CI_COMMIT_SHORT_SHA
  only:
    - stageX

build:master:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_PROD
    BUILD_VERSION: Master:$CI_COMMIT_SHORT_SHA
  only:
    - master

build:production:
  <<: *build_script
  variables:
    BUILD_CONFIG: $BUILD_CONFIG_PROD
    BUILD_VERSION: CI_COMMIT_TAG
  only:
    - /^([0-9]+\.){2}([0-9]+)+(\.[0-9]+)?$/
  except:
    - branches


# RELEASE ==============================
.release_script: &release_script
  stage: deploy
  image: docker:stable
  tags: 
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $BUILD_IMAGE    
    - docker login  -u $AZURE_APP_ID -p $AZURE_APP_SECRET $AZURE_ACR_SERVER   
    - docker tag $BUILD_IMAGE $DEPLOY_IMAGE
    - docker push $DEPLOY_IMAGE

release:stage:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:stage
  only:
    - stageX

release:master:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:master
  only:
    - master    

release:production:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:$CI_COMMIT_TAG
  only:
    - /^([0-9]+\.){2}([0-9]+)+(\.[0-9]+)?$/
  except:
    - branches

release:latest:
  <<: *release_script
  variables:
    DEPLOY_IMAGE: $AZURE_ACR_SERVER/apps-ui:latest
  only:
    - /^([0-9]+\.){2}([0-9]+)+(\.[0-9]+)?$/
  except:
    - branches


# DEPLOY ==============================
.deploy_script: &deploy_script
    stage: deploy
    image: dtzar/helm-kubectl
    tags: 
      - docker
    script:
      - echo $KUBE_CLUSTER_CA > deploy.crt
      - kubectl config set-cluster k8s --server="$KUBE_CLUSTER" --certificate-authority=deploy.crt --embed-certs=true
      - kubectl config set-credentials ci-cd --token="$KUBE_USER_TOKEN"
      - kubectl config set-context k8s --cluster=k8s --user=ci-cd
      - kubectl config use-context k8s    
      - kubectl config view
      - kubectl get all --insecure-skip-tls-verify=true
      - kubectl --record deployment.apps/$DEPLOYMENT_NAME set image deployment.v1.apps/$DEPLOYMENT_NAME $DEPLOYMENT_CONTAINER_NAME=$DEPLOY_IMAGE --namespace=$DEPLOYMENT_NAMESPACE 
      - kubectl patch deployment.apps/$DEPLOYMENT_NAME -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"lastUpdateDateTime\":\"`date +'%s'`\"}}}}}" --namespace=$DEPLOYMENT_NAMESPACE       
      
deploy:staging:
  <<: *deploy_script
  variables:
    DEPLOYMENT_NAME: apps-ui-deployment
    DEPLOYMENT_CONTAINER_NAME: app
    DEPLOY_IMAGE: ${AZURE_ACR_SERVER}/apps-ui:stage    
    DEPLOYMENT_NAMESPACE: apps-staging        
  only:
    - stage




