apiVersion: v1
kind: Namespace
metadata:
  name:  apps-development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-ui-app
  namespace: apps-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-ui-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: apps-ui-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: app                    
        image: romacloud.azurecr.io/apps-ui:develop        
        ports:
        - containerPort: 80
        env:
        - name: NG_ENVIRONMENT
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: apps-ui-http
  namespace: apps-development
  labels:
    app: apps-ui-app
spec:  
  ports:
  - port: 8081    
    protocol: TCP
    targetPort: 80
  selector:
    app: apps-ui-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
  name: apps-ui
  namespace: apps-development
  labels:
    app: apps-ui-app
spec:
  ingressClassName: nginx
  rules:
  - host: apps-dev.roma-cloud.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: apps-ui-http
            port:
              number: 8081     