apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apps-ui-stage
  namespace: development
  labels:
      app: apps-ui-stage
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: apps-ui-stage
    spec:
      containers:
      - name: apps-ui-stage
        image: registry.gitlab.com/roma-code/apps/apps-ui:stage
        ports:
        - containerPort: 80
      nodeSelector:
        env: development
      imagePullSecrets:
      - name: gitlab-regcred-romacode
---
apiVersion: v1
kind: Service
metadata:
  name: apps-ui-stage
  namespace: development
  labels:
    app: apps-ui-stage
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: apps-ui-stage
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($http_x_forwarded_proto = 'http'){
        return 301 https://$host$request_uri;
      }
  name: apps-ui-stage
  namespace: development
  labels:
    app: apps-ui-stage
spec:
  rules:
  - host: apps-stage.roma-cloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apps-ui-stage
          servicePort: 8080      