apiVersion: v1
kind: Namespace
metadata:
  name:  apps-production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-ui-deployment
  namespace: apps-production  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps-ui-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: apps-ui-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: app
        image: romacloud.azurecr.io/apps-ui:latest
        ports:
        - containerPort: 80      
---
apiVersion: v1
kind: Service
metadata:
  name: apps-ui-service
  namespace: apps-production
  labels:
    app: apps-ui-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: apps-ui-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($http_x_forwarded_proto = 'httpX'){
        return 302 https://$host$request_uri;
      }
  name: apps-ui-ingress
  namespace: apps-production
  labels:
    app: apps-ui-app
spec:
  rules:
  - host: apps.roma-cloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apps-ui-service
          servicePort: 8080      